apiVersion: v1
kind: Service
metadata:
  name: cafe-svc-nodeport
  labels:
    app: cafe
spec:
  selector:
    app: cafe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
