apiVersion: v1
kind: Service
metadata:
  name: cafe-svc-lb
  labels:
    app: cafe
spec:
  selector:
    app: cafe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
